<?php 

return array(
        'nf' => array(
            1 => 'Gossip', //If creature has more gossip options, add this flag to bring up a menu.
            2 => 'Quest Giver', //Any creature giving or taking quests needs to have this flag.
            16 => 'Trainer', //Allows the creature to have a trainer list to teach spells
            32 => 'Class Trainer', //
            64 => 'Profession Trainer', //
            128 => 'Vendor', //Any creature selling items needs to have this flag.
            256 => 'Vendor Ammo', //
            512 => 'Vendor Food', //
            1024 => 'Vendor Poison', //
            2048 => 'Vendor Reagent', //
            4096 => 'Repairer', //Creatures with this flag can repair items.
            8192 => 'Flight Master', //Any creature serving as fly master has this.
            16384 => 'Spirit Healer', //Makes the creature invisible to alive characters and has the resurrect function.
            32768 => 'Spirit Guide', //
            65536 => 'Innkeeper', //Creatures with this flag can set hearthstone locations.
            131072 => 'Banker', //Creatures with this flag can show the bank
            262144 => 'Petitioner', //
            524288 => 'Tabard Designer', //Allows the designing of guild tabards.
            1048576 => 'Battlemaster', //Creatures with this flag port players to battlegrounds.
            2097152 => 'Auctioneer', //Allows creature to display auction list.
            4194304 => 'Stable Master', //Has the option to stable pets for hunters.
            8388608 => 'Guild Banker', //
            16777216 => 'Spellclick', //Needs data on npc_spellclick_spells table
            67108864 => 'Mailbox', //NPC will act like a mailbox (opens mailbox with right-click)
        ),
        'uf' => array(
            1 => 'UNIT_FLAG_SERVER_CONTROLLED', //
            2 => 'UNIT_FLAG_NON_ATTACKABLE', //
            4 => 'UNIT_FLAG_DISABLE_MOVE', //	Prevents the creature from moving at all
            8 => 'UNIT_FLAG_PVP_ATTACKABLE', //	Allows to apply pvp rules to attackable state in addition to faction dependent state
            16 => 'UNIT_FLAG_RENAME', //
            32 => 'UNIT_FLAG_PREPARATION', //	Don't take reagents for spells with SPELL_ATTR_EX5_NO_REAGENT_WHILE_PREP
            64 => 'UNIT_FLAG_UNK_6', //	not sure what it does, but it is needed to cast nontriggered spells in smart_scripts
            128 => 'UNIT_FLAG_NOT_ATTACKABLE_1', // is NON_PVP_ATTACKABLE
            256 => 'UNIT_FLAG_IMMUNE_TO_PC', //	disables combat/assistance with PlayerCharacters (PC)
            512 => 'UNIT_FLAG_IMMUNE_TO_NPC', //	disables combat/assistance with NonPlayerCharacters (NPC)
            1024 => 'UNIT_FLAG_LOOTING', //	Loot animation
            2048 => 'UNIT_FLAG_PET_IN_COMBAT', //	In combat? 2.0.8
            4096 => 'UNIT_FLAG_PVP', //	Changed in 3.0.3
            8192 => 'UNIT_FLAG_SILENCED', //	Can't cast spells
            16384 => 'UNIT_FLAG_CANNOT_SWIM', //	2.0.8
            32768 => 'UNIT_FLAG_SWIMMING', //
            65536 => 'UNIT_FLAG_NON_ATTACKABLE_2', //
            131072 => 'UNIT_FLAG_PACIFIED', //	Creature will not attack
            262144 => 'UNIT_FLAG_STUNNED', //	3.0.3 ok
            524288 => 'UNIT_FLAG_IN_COMBAT', //
            1048576 => 'UNIT_FLAG_TAXI_FLIGHT', //	Disable casting at client side spell not allowed by taxi flight (mounted?), probably used with           2097152 => 'DISARMED', //	3.0.3, disable melee spells casting..., "Required melee weapon" added to melee spells tooltip.
            2097152 => 'UNIT_FLAG_DISARMED',
            4194304 => 'UNIT_FLAG_CONFUSED', //
            8388608 => 'UNIT_FLAG_FLEEING', //
            16777216 => 'UNIT_FLAG_POSSESSED', //	Used in spell Eyes of the Beast for pet... let attack by controlled creature. Also used by Vehicles (PCV).
            33554432 => 'UNIT_FLAG_NOT_SELECTABLE', //	Can't be selected by mouse or with /target {name} command.
            67108864 => 'UNIT_FLAG_SKINNABLE', //
            134217728 => 'UNIT_FLAG_MOUNT', //	The client seems to handle it perfectly. Also used when making custom mounts.
            268435456 => 'UNIT_FLAG_UNK_28', //
            536870912 => 'UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT', //	Used in Feing Death spell or NPC will play dead.
            1073741824 => 'UNIT_FLAG_SHEATHE', //
            2147483648 => 'UNIT_FLAG_IMMUNE', //
        ),
        'tf' => array(
            1 => 'CREATURE_TYPE_FLAG_TAMEABLE',	// Makes the mob tameable (must also be a beast and have family set)
            2 => 'CREATURE_TYPE_FLAG_VISIBLE_TO_GHOSTS',	// Creature are also visible for not alive player. Allow gossip interaction if npcflag allow?
            4 => 'CREATURE_TYPE_FLAG_BOSS_MOB',	// Changes creature's visible level to "??" in the creature's portrait - Immune to Knockback.
            8 => 'CREATURE_TYPE_FLAG_DO_NOT_PLAY_WOUND_ANIM',	// Does not play wound animation on parry.
            16 => 'CREATURE_TYPE_FLAG_NO_FACTION_TOOLTIP', // 	Hides tooltip faction.
            32 => 'CREATURE_TYPE_FLAG_MORE_AUDIBLE',
            64 => 'CREATURE_TYPE_FLAG_SPELL_ATTACKABLE',	// Spell attackable.
            128	 =>	'CREATURE_TYPE_FLAG_INTERACT_WHILE_DEAD',	// Player can interact with the creature if its dead (not player dead)
            256	 =>	'CREATURE_TYPE_FLAG_SKIN_WITH_HERBALISM' ,// makes mob herbable
            512	 =>	'CREATURE_TYPE_FLAG_SKIN_WITH_MINING',	// Makes mob minable
            1024 => 'CREATURE_TYPE_FLAG_NO_DEATH_MESSAGE',	// Does not combatlog death.
            2048 => 'CREATURE_TYPE_FLAG_ALLOW_MOUNTED_COMBAT',	// Creature can remain mounted when entering combat
            4096 => 'CREATURE_TYPE_FLAG_CAN_ASSIST',// 	Can aid any player in combat if in range?
            8192 => 'CREATURE_TYPE_FLAG_NO_PET_BAR',// 	Is using pet bar.
            16384 => 'CREATURE_TYPE_FLAG_MASK_UID',	
            32768 => 'CREATURE_TYPE_FLAG_SKIN_WITH_ENGINEERING',// 	Makes mob lootable by engineer
            65536 => 'CREATURE_TYPE_FLAG_TAMEABLE_EXOTIC',	// Tamable as an exotic pet. Normal tamable flag must also be set.
            131072 => 'CREATURE_TYPE_FLAG_USE_MODEL_COLLISION_SIZE',	// Collision related. (always using default collision box?)
            262144 => 'CREATURE_TYPE_FLAG_ALLOW_INTERACTION_WHILE_IN_COMBAT',// 	Is siege weapon.
            524288 => 'CREATURE_TYPE_FLAG_COLLIDE_WITH_MISSILES', // Projectiles can collide with this creature - interacts with TARGET_DEST_TRAJ
            1048576 => 'CREATURE_TYPE_FLAG_NO_NAME_PLATE',	// Hides nameplate.
            2097152 => 'CREATURE_TYPE_FLAG_DO_NOT_PLAY_MOUNTED_ANIMATIONS',	// Does not play mounted animations.
            4194304 => 'CREATURE_TYPE_FLAG_LINK_ALL',	
            8388608 => 'CREATURE_TYPE_FLAG_INTERACT_ONLY_WITH_CREATOR', // Can only interact with its creator.
            16777216 => 'CREATURE_TYPE_FLAG_DO_NOT_PLAY_UNIT_EVENT_SOUNDS',
            33554432 => 'CREATURE_TYPE_FLAG_HAS_NO_SHADOW_BLOB',
            67108864 => 'CREATURE_TYPE_FLAG_TREAT_AS_RAID_UNIT',
            134217728 => 'CREATURE_TYPE_FLAG_FORCE_GOSSIP',	// Allows the creature to display a single gossip option.
            268435456 => 'CREATURE_TYPE_FLAG_DO_NOT_SHEATHE',
            536870912 => 'CREATURE_TYPE_FLAG_DO_NOT_TARGET_ON_INTERACTION',
            1073741824 => 'CREATURE_TYPE_FLAG_DO_NOT_RENDER_OBJECT_NAME',
            2147483648 => 'CREATURE_TYPE_FLAG_QUEST_BOSS',
        ),
        'itf' => array(
            1 => 'Ground',
            2 => 'Water',
            4 => 'Flying',
            8 => 'Rooted',
        ),
        'mim' => array(
            1 => 'MECHANIC_CHARM', //
            2 => 'MECHANIC_DISORIENTED', //
            4 => 'MECHANIC_DISARM', //
            8 => 'MECHANIC_DISTRACT', //
            16 => 'MECHANIC_FEAR', //
            32 => 'MECHANIC_GRIP', //Death Grip and similar effects
            64 => 'MECHANIC_ROOT', //
            128 => 'MECHANIC_PACIFY', //Not used: 0 spells with this mechanic
            256 => 'MECHANIC_SILENCE', //
            512 => 'MECHANIC_SLEEP', //
            1024 => 'MECHANIC_SNARE', //
            2048 => 'MECHANIC_STUN', //
            4096 => 'MECHANIC_FREEZE', //
            8192 => 'MECHANIC_KNOCKOUT', //Incapacitate effects such as Repetance (Paladin)
            16384 => 'MECHANIC_BLEED', //
            32768 => 'MECHANIC_BANDAGE', //Healing etc.
            65536 => 'MECHANIC_POLYMORPH', //
            131072 => 'MECHANIC_BANISH', //
            262144 => 'MECHANIC_SHIELD', //
            524288 => 'MECHANIC_SHACKLE', //Shackle Undead only
            1048576 => 'MECHANIC_MOUNT', //Any effect that summons a mount
            2097152 => 'MECHANIC_INFECTED', //Frost Fever, Blood Plague etc.
            4194304 => 'MECHANIC_TURN', //e.g. Turn Evil
            8388608 => 'MECHANIC_HORROR', //e.g. Death Coil (Warlock)
            16777216 => 'MECHANIC_INVULNERABILITY', //Forbearance, Nether Protection, Diplomatic Immunity only
            33554432 => 'MECHANIC_INTERRUPT', //
            67108864 => 'MECHANIC_DAZE', //
            134217728 => 'MECHANIC_DISCOVERY', //Any Create Item effect
            268435456 => 'MECHANIC_IMMUNE_SHIELD', //Divine Shield, Ice Block, Hand of Protection...
            536870912 => 'MECHANIC_SAPPED', //
            1073741824 => 'MECHANIC_ENRAGED', //
        ),
        'ssim' => array(
            1 => 'SPELL_SCHOOL_MASK_NORMAL',
            2 => 'SPELL_SHCOOL_MASK_HOLY',
            4 => 'SPELL_SCHOOL_MASK_FIRE',
            8 => 'SPELL_SCHOOL_MASL_NATURE',
            16 => 'SPELL_SCHOOL_MASK_FROST',
            32 => 'SPELL_SCHOOL_MASK_SHADOW',
            64 => 'SPELL_SCHOOL_MASK_ARCANE',
        ),
        'fe' => array(
            1 => 'CREATURE_FLAG_EXTRA_INSTANCE_BIND', //	creature kill binds instance to killer and killer's group
            2 => 'CREATURE_FLAG_EXTRA_CIVILIAN', //	creature does not aggro (ignore faction/reputation hostility)
            4 => 'CREATURE_FLAG_EXTRA_NO_PARRY', //	creature does not parry
            8 => 'CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN', //	creature does not counter-attack at parry
            16 => 'CREATURE_FLAG_EXTRA_NO_BLOCK',	//creature does not block
            32 => 'CREATURE_FLAG_EXTRA_NO_CRUSHING_BLOWS', //	creature does not do crush-attacks
            64 => 'CREATURE_FLAG_EXTRA_NO_XP',	//creature kill does not give XP
            128	=> 'CREATURE_FLAG_EXTRA_TRIGGER', //	creature is trigger-NPC (invisible to players only)
            256	=> 'CREATURE_FLAG_EXTRA_NO_TAUNT', //	creature is immune to taunt-auras and "attack me"-effects
            512 => 'CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE',	//creature won't update movement flags
            1024 =>	'CREATURE_FLAG_EXTRA_GHOST_VISIBILITY',	//creature will be only visible for dead players
            2048 =>	'CREATURE_FLAG_EXTRA_UNUSED_12', //	creature will use offhand attacks
            4096 =>	'CREATURE_FLAG_EXTRA_NO_SELL_VENDOR',	//players can't sell items to this vendor
            8192 => 'CREATURE_FLAG_EXTRA_IGNORE_COMBAT',
            16384 => 'CREATURE_FLAG_EXTRA_WORLDEVENT', //	custom flag for world events (left room for merging)
            32768 => 'CREATURE_FLAG_EXTRA_GUARD', //	creature is a guard (Will ignore feign death and vanish)
            65536 => 'CREATURE_FLAG_EXTRA_IGNORE_FEIGN_DEATH',
            131072 => 'CREATURE_FLAG_EXTRA_NO_CRIT', //	creature does not do critical strikes
            262144 => 'CREATURE_FLAG_EXTRA_NO_SKILLGAIN',	//creature won't increase weapon skills
            524288 => 'CREATURE_FLAG_EXTRA_OBEYS_TAUNT_DIMINISHING_RETURNS',	//creature taunt is subject to diminishing returns
            1048576 => 'CREATURE_FLAG_EXTRA_ALL_DIMINISH', //	Creature is subject to all diminishing returns
            2097152	=> 'CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ', // NPCs can help with killing this creature and player will still be credited if he tags the creature
            4194304 => 'CREATURE_FLAG_EXTRA_AVOID_AOE',
            8388608 => 'CREATURE_FLAG_EXTRA_NO_DODGE',
            16777216 => 'CREATURE_FLAG_EXTRA_UNUSED_25',
            33554432 => 'CREATURE_FLAG_EXTRA_UNUSED_26',
            67108864 => 'CREATURE_FLAG_EXTRA_UNUSED_27',
            134217728 => 'CREATURE_FLAG_EXTRA_UNUSED_28',
            268435456 => 'CREATURE_FLAG_EXTRA_DUNGEON_BOSS',
            536870912 => 'CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING',
            1073741824 => 'CREATURE_FLAG_EXTRA_IMMUNITY_KNOCKBACK',	// creature will immune all knockback effects
            2147483648 => 'CREATURE_FLAG_EXTRA_HARD_RESET',
        ),
    );
